### ISSUE TITLE
support for multiple time zones in post times

### ISSUE THREAD

**Issue by alexreyes** [alexreyes/perma-quarantine-notes-web#11]

**Comment by aidanok** [comment]
So, this is relevant for both this issue and #12  

When we write a Tx to Arweave it has a timestamp, the block that the Tx is in has a timestamp, and it's impossible for users to forge or fake this, so we should look to use this. 

If you query with ArQL , it will order transactions by most recent to oldest in the results.  

If we allow users to tag their location, and use the transaction timestamp we have most of the information we need.  

We could grab the clients timezone from JavaScript, but it might be better make the 'location' of the post a required field, since the clients timezone is not particularly reliable, and we always trusting the user to tell us _where_ the note is relevant to.

**Comment by alexreyes** [comment]
Used Luxon to get the user's current date/time from their computer. Should be the simplest way to do this and solve the time zone problem: 65b5d57d3c26fb7dadb62841b415b1eb736d65d4
